name: Deploy to AWS EKS

on:
  push:
    branches: [ '**' ]  # Adjust branch name as needed
    paths:
      - 'k8s/*.*' 
      - '.github/workflows/deploy.yml'
  workflow_dispatch:    # Allows manual triggering from GitHub UI

env:
  AWS_REGION: 'ap-southeast-1'  
  EKS_CLUSTER_NAME: "nasir-eks" 

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Configure AWS 
      run: |
        # Install AWS CLI if not already available
        curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o awscliv2.zip \
        && unzip awscliv2.zip \
        && ./aws/install \
        && rm -rf aws awscliv2.zip
    
        # Configure AWS credentials
        mkdir -p ~/.aws
    
        # Create credentials file
        cat > ~/.aws/credentials << EOF
        [default]
        aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}
        EOF
    
        # Create config file with region
        cat > ~/.aws/config << EOF
        [default]
        region=${{ env.AWS_REGION }}
        output=json
        EOF
    
        # Verify credentials are working (optional)
        aws sts get-caller-identity
        
    - name: Configure Kubectl 
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/bin/
        kubectl version --client

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER_NAME }}
        kubectl cluster-info
        

    - name: Deploy to EKS
      run: |
        cd k8s
        kubectl apply -f configmap.yml
        kubectl apply -f deployment.yml
        kubectl apply -f service.yml
        kubectl apply -f ingress.yml

    - name: Verify deployment
      run: |
        kubectl get pods -l app=clock-app
        kubectl get svc clock-app
        kubectl get ingress clock-app-ingress